<a href="https://colab.research.google.com/github/ugbana1/Abtractive-Summary/blob/main/TensorflowTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d =tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


One Dimensional Array

In [10]:
tensor_one_d =tf.constant([2,0,-3,8,90.0])

In [11]:
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


Creating a 2D tensor



In [12]:
tensor_two_d=tf.constant([
    [1,2,0],
    [2,3,4],
    [3,5,6]

])

In [13]:
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [2 3 4]
 [3 5 6]], shape=(3, 3), dtype=int32)


Creating 3 D tensors


In [15]:
tensor_three_d=tf.constant([
    [[1,5,0],
     [3,5,-1]],
    [[6,8,0],
     [3,8,9]],
    [[6,5,4],[0,3,7]]

])

In [16]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  5  0]
  [ 3  5 -1]]

 [[ 6  8  0]
  [ 3  8  9]]

 [[ 6  5  4]
  [ 0  3  7]]], shape=(3, 2, 3), dtype=int32)


In [20]:
tensor_three_d.shape

TensorShape([3, 2, 3])

In [24]:
tensor_four_d=tf.constant([[
     [[1,5,0],
     [3,5,-1]],
    [[6,8,0],
     [3,8,9]],
    [[6,5,4],[0,3,7]],
      [[1,5,0],
     [3,5,-1]],
    [[6,8,0],
     [3,8,9]],
    [[6,5,4],[0,3,7]],
      [[1,5,0],
     [3,5,-1]],
    [[6,8,0],
     [3,8,9]],
    [[6,5,4],[0,3,7]]
]])

In [25]:
print(tensor_four_d)

tf.Tensor(
[[[[ 1  5  0]
   [ 3  5 -1]]

  [[ 6  8  0]
   [ 3  8  9]]

  [[ 6  5  4]
   [ 0  3  7]]

  [[ 1  5  0]
   [ 3  5 -1]]

  [[ 6  8  0]
   [ 3  8  9]]

  [[ 6  5  4]
   [ 0  3  7]]

  [[ 1  5  0]
   [ 3  5 -1]]

  [[ 6  8  0]
   [ 3  8  9]]

  [[ 6  5  4]
   [ 0  3  7]]]], shape=(1, 9, 2, 3), dtype=int32)


In [26]:
print(tensor_four_d.shape)

(1, 9, 2, 3)


Tensor Casting

In [27]:
tensor_one_d=tf.constant([2,0,-3],dtype=tf.float32)
tensor_cast=tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_cast)
print(tensor_one_d)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)
tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)


In [28]:
tensor_boo=tf.constant([True,True,False])
print(tensor_boo)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [29]:
tensor_string=tf.constant(['Hello World','Hi '])
print(tensor_string)

tf.Tensor([b'Hello World' b'Hi '], shape=(2,), dtype=string)


In [30]:
import numpy as np
np_array=np.array([1,2,3])
print(np_array)

[1 2 3]


In [31]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [42]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


Fill In Tensor

In [43]:
fill_tensor=tf.fill(
    [3,4], 7, name=None
)
print(fill_tensor)

tf.Tensor(
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]], shape=(3, 4), dtype=int32)


ONES METHOD

In [45]:
ones_tensor=tf.ones(
    [7,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(7, 4), dtype=float32)


In [46]:
input1=[
    [2,3,4],
    [3,4,7]
        ]
ones_like_tensor=tf.ones_like(
    input1, dtype=None, name=None
)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [47]:
zeros_tensors=tf.zeros(
    [3,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensors)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [55]:
tensor_size= tf.constant([[1, 1, 1], [2, 2,2]],)
print(tf.size(tensor_size,out_type=tf.bool))


tf.Tensor(True, shape=(), dtype=bool)


In [59]:
random_tensor=tf.random.uniform(
    [5,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([0.9530711  0.2717656  0.84152687 0.24421525 0.24285007], shape=(5,), dtype=float32)


In [66]:
tf.random.set_seed(5)
tf.random.uniform(shape=[2,3], maxval=3, dtype=tf.int32, seed=10)

print(tf.random.uniform(shape=[2,3], maxval=3, dtype=tf.int32, seed=10))




tf.Tensor(
[[0 1 1]
 [1 2 2]], shape=(2, 3), dtype=int32)


In [71]:
tf.random.set_seed(123)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2772479], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.2772479], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7429987], dtype=float32)>)


Tensorflow Indexing

In [76]:
tensor_indexed=tf.constant([2,3,4,5,66,7])
print(tensor_indexed)
print(tensor_indexed[0:4])
print(tensor_indexed[1:4+1])

tf.Tensor([ 2  3  4  5 66  7], shape=(6,), dtype=int32)
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.Tensor([ 3  4  5 66], shape=(4,), dtype=int32)


In [79]:
tensor_three_d=tf.constant([
    [[1,5,0],
     [3,5,-1]],
    [[6,8,0],
     [3,8,9]],
    [[6,5,4],[0,3,7]]

])
print(tensor_three_d[:2,:])

tf.Tensor(
[[[ 1  5  0]
  [ 3  5 -1]]

 [[ 6  8  0]
  [ 3  8  9]]], shape=(2, 2, 3), dtype=int32)


In [81]:
#Reduce Sum
tensor_three_d=tf.constant([
    [[1,5,0],
     [3,5,-1]],
    [[6,8,0],
     [3,8,9]],
    [[6,5,4],[0,3,7]]

])
print(tf.math.reduce_sum(
    tensor_three_d, axis=None, keepdims=False, name=None
))

tf.Tensor(72, shape=(), dtype=int32)


In [82]:
tensor_string =tf.constant(["Hello","I am","a string"])
print(tensor_string)

tf.Tensor([b'Hello' b'I am' b'a string'], shape=(3,), dtype=string)


In [83]:
tf.strings.join(tensor_string,separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello I am a string'>